project: NotifySync
version: 4.7.16
changelog:
  - HARMONISATION : Alignement sur le standard de qualité Jellyfin.Xtream.
  - TRANSPARENCE : Migration du scan de l'historique vers une Tâche Planifiée (Tableau de bord Jellyfin).
  - Rigueur : Activation des analyseurs StyleCop et multithreading.
  - MÉTADONNÉES : Mise à jour des informations projet (Auteurs: Peterdu1109, ElieM).
  - STABILITÉ : Build finale avec 0 avertissement stricts.
