project: NotifySync
version: 4.7.17.10
targetAbi: 10.11.0.0
build:
  - FIX : Filtrage intelligent des items de streaming (XFusion VOD/Séries) — exclusion automatique des contenus IPTV non-locaux.
  - FIX : Correction du statut "Vu/Non vu" par épisode (suppression de la propagation série → épisodes).
  - FIX : Le clic sur une série dans la cloche ne marque plus tous les épisodes comme vus.
  - FIX : Affichage du nombre réel d'épisodes non vus par l'utilisateur (au lieu du total).
  - FIX : Désactivation du cache navigateur sur Client.js pour prise en compte immédiate des mises à jour.
  - STABILITÉ : Filtrage configurable des bibliothèques par CategoryMapping (avec/sans bibliothèque cochée).
  - STABILITÉ : Build finale avec 0 avertissement stricts sur .NET 9.0.
